credentials:
  usernames:
    test_user:
      email: s.ogura@gpm.co.jp
      name: 小椋
      password: LkHg0001
      company: ジーピーエム株式会社
      tel: 050-5497-7359
cookie:
  expiry_days: 30
  key: random_signature_key
  name: rakuten_tool_cookie
preauthorized:
  emails: []